### ISSUE TITLE
* bis 15.01. Abstract für Heidelberger Frühjahrssymposium

### ISSUE THREAD

**Issue by graefea** [BIH-CEI/ERKER#24]
```
Liebe alle, hiermit leite ich eine Info weiter, die ich über einen anderen Verteiler bekommen habe. 
Viele Grüße Sophie Liebe Kolleginnen und Kollegen, am 8.5.2024 veranstalten wir in Heidelberg das zweite Frühjahrssymposium Medizinische Informatik. Themenschwerpunkt sind wieder Medizinische Informationssysteme. 
Dieses Mal planen wir verstärkt auch englische Beiträge. Wir freuen uns über Einreichungen aus Ihren Teams - bitte gerne den Call for Abstracts verteilen. Herzliche Grüße, Martin Dugas und Petra Knaup ==================================================================================================== Betreff: Call for Abstracts und Save the Date | 2. Heidelberger Frühjahrssymposium Medizinische Informatik 8.5.2024 Sehr geehrte Kolleginnen und Kollegen, nach dem erfolgreichen MI-Symposium 2023 möchten wir den wissenschaftlichen Austausch in Deutschland und Europa zum Thema Medizinische Informationssysteme für innovative Forschung und Versorgung weiter fördern. Wir laden Sie daher schon heute herzlich zum 2. Heidelberger Frühjahrssymposium Medizinische Informatik am Mittwoch, 8. Mai 2024 ein. Die Einreichungsfrist für Abstracts ist der 15.01.2024. Über Beiträge von Ihnen und aus Ihrem Team freuen wir uns. Bitte verteilen Sie gerne diese Information. Nähere Informationen finden Sie hier: http://ukhd.de/mi-symposium Mit freundlichen Grüßen Martin Dugas und Petra Knaup Univ.-Prof. Dr. med. Dipl.-Inform. Martin Dugas Direktor | Institut für Medizinische Informatik Universitätsklinikum Heidelberg | Im Neuenheimer Feld 130.3 | 69120 Heidelberg Tel. +49 6221 56-5060 | E-Mail: Martin.Dugas@med.uni-heidelberg.de https://www.klinikum.uni-heidelberg.de/ | https://www.klinikum.uni-heidelberg.de/mi
```

**Comment by frehburg** [comment]
am 8.5.2024 veranstalten wir in Heidelberg das zweite Frühjahrssymposium Medizinische Informatik.

Themenschwerpunkt sind wieder Medizinische Informationssysteme.

Dieses Mal planen wir verstärkt auch englische Beiträge.

Wir freuen uns über Einreichungen aus Ihren Teams - bitte gerne den Call for Abstracts verteilen.

Herzliche Grüße,

Martin Dugas und Petra Knaup

====================================================================================================

Betreff: Call for Abstracts und Save the Date | 2. Heidelberger Frühjahrssymposium Medizinische Informatik 8.5.2024

Sehr geehrte Kolleginnen und Kollegen,

nach dem erfolgreichen MI-Symposium 2023 möchten wir den wissenschaftlichen Austausch in Deutschland und Europa

zum Thema Medizinische Informationssysteme für innovative Forschung und Versorgung weiter fördern.

Wir laden Sie daher schon heute herzlich zum 2. Heidelberger Frühjahrssymposium Medizinische Informatik am Mittwoch, 8. Mai 2024 ein.

Die Einreichungsfrist für Abstracts ist der 15.01.2024. Über Beiträge von Ihnen und aus Ihrem Team freuen wir uns.
Bitte verteilen Sie gerne diese Information. Nähere Informationen finden Sie hier: ukhd.de/mi-symposium

Mit freundlichen Grüßen

Martin Dugas und Petra Knaup





Univ.-Prof. Dr. med. Dipl.-Inform. Martin Dugas

Direktor | Institut für Medizinische Informatik


Universitätsklinikum Heidelberg | Im Neuenheimer Feld 130.3 | 69120 Heidelberg

Tel. +49 6221 56-5060 | E-Mail: [Martin.Dugas@med.uni-heidelberg.de](mailto:Martin.Dugas@med.uni-heidelberg.de)

https://www.klinikum.uni-heidelberg.de/ | https://www.klinikum.uni-heidelberg.de/mi

**Comment by frehburg** [comment]
Generell Interop, nicht erker spezifisch
